### ISSUE TITLE
Cannot build with CMake  - ALLEGRO_HOME not defined

### ISSUE THREAD

**Issue by Raimmaster** [dradtke/allegro_tiled#10]
Hello, Dradtke, it seems there's an error with your latest commit:
https://github.com/dradtke/allegro_tiled/commit/eb66840f907742a010888861b802e194cad93f7b

I cloned this repo for a project of mine, yet when I ran cmake I got the following errors:
CMake Error at cmake/Utils.cmake:65 (message):
  ALLEGRO_HOME is not defined.

It appears I wasn't the only one, and I wanted to report it. By the way, I'm using Linux Mint 17.1.

**Comment by Raimmaster** [comment]
By the way, when I checked out to this commit (8c113c51bbaa5ddcea1244bba3b92857129e873e), I managed to run cmake without problems.

**Comment by dradtke** [comment]
That's odd, do you have `pkg-config` installed? It should only be attempting to use `ALLEGRO_HOME` if that isn't installed. If so, what Allegro package are you using?

**Comment by ElectricSolstice** [comment]
Well, I do have pkg-config installed on my system (debian), and if I start fresh by git clone and then trying "cmake .", this is the error that occurs:

```
cmake .
-- The C compiler identification is GNU 4.7.2
-- The CXX compiler identification is GNU 4.7.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
pkg-config is not installed on this system, using environment variables.
CMake Error at cmake/Utils.cmake:65 (message):
  ALLEGRO_HOME is not defined.
Call Stack (most recent call first):
  CMakeLists.txt:71 (find_env_deps)


-- Configuring incomplete, errors occurred!
```

**Comment by Raimmaster** [comment]
I get the same error as ElectricSoltice. pkg-config is in its latest version according to my package manager. I'm using Allegro 5.0.11.

**Comment by dradtke** [comment]
Can you try changing line 16 in CMakeLists.txt from `if(PkgConfig_FOUND)` to `if(PKG_CONFIG_FOUND)` and see if that works?

**Comment by ElectricSolstice** [comment]
That seems to have fixed it on my computer.

**Comment by dradtke** [comment]
Cool, I just committed that change to master. @Raimmaster , can you check to see if it works for you too?

The problem here was that I read the documentation too literally and was unable to test it, so I assumed the search for package `PkgConfig` would set `PkgConfig_FOUND` to true as listed [here](http://www.cmake.org/cmake/help/v3.0/command/find_package.html). But the [FindPkgConfig](http://www.cmake.org/cmake/help/v3.0/module/FindPkgConfig.html) module sets `PKG_CONFIG_FOUND` to true, so my guess is that either a) CMake automatically adjusts module names to be upper-snake case when setting variables, or b) `find_package(PkgConfig)` uses the `FindPkgConfig` module under the hood.

**Comment by Raimmaster** [comment]
I just tested changing to PKG_CONFIG_FOUND and it does the trick. Thanks.

**Comment by dradtke** [comment]
Awesome, thanks for the update.
