### ISSUE TITLE
al_open_map fails on absolute directory path

### ISSUE THREAD

**Issue by ElectricSolstice** [dradtke/allegro_tiled#11]
As far as I can tell, it's not documented anywhere about this. However, al_open_map currently requires relative paths because an absolute path will cause a segmentation fault.
For example, if you change line 19 of main.c of the example to an absolute path like this

```
#define "/home/browser/Downloads/allegro_tiled/example/data/maps"
```

,I get this error when I run the example.

```
./example
I/O warning : failed to load external entity "level1.tmx"                                                                                                               
Error: failed to parse map data: level1.tmx                                                                                                                             
Segmentation fault 
```

**Comment by dradtke** [comment]
Ah, I see what it's doing. If the passed in directory is absolute, then `al_join_paths()` leaves the directory unmodified, so it cd's to the current directory (which is redundant), then fails to find the map file and returns NULL, which the example doesn't expect.

I pushed a fix to `absolute_path_fix`, which listens to the return result of `al_join_paths()`, and if it fails, cd's instead directly to the path that was supplied, since we now know it's absolute. Can you try checking out that branch and see if it works? I don't have a working build environment at this computer currently.

**Comment by ElectricSolstice** [comment]
Thanks. The fix seems to work on the example for me.

**Comment by Raimmaster** [comment]
I tested this branch and it also works on absolute paths for me too. Regarding this issue, I seem to be getting the same errors with relative paths. Discussing in the Allegro IRC, it seems this gist someone made last night seems to do the trick:

https://gist.github.com/SiegeLord/a965ded48ddb50b1f96d

**Comment by dradtke** [comment]
The idea was to have the path be relative to the running executable, not necessarily the working directory, because that makes it easier to package for distribution and know that the paths will still work regardless of how or from where the game is started. The Allegro docs [recommend](http://alleg.sourceforge.net/a5docs/5.0.10/system.html#al_get_standard_path) it for that reason, which is why I went with it.

I see a couple options:

1. Change it to be relative to the working directory instead of to the executable. This is the fix in the gist, and while it works, I think it could cause headaches down the road when it comes to packaging and distribution.

2. Provide a parameter telling `al_open_map()` what relative paths should be considered relative to: the working directory, or the executable.

3. Check one, and then the other, e.g. check to see if there's a "packaged" version relative to the executable first, check it relative to the working directory if it's not found, and only if both are missing have the method fail.

I'm thinking option 3 would end up being the best one here, since it would then work for all scenarios without requiring additional configuration or parameters. Thoughts?

**Comment by ElectricSolstice** [comment]
Out of the 3 options given, the one I like the most is # 2. Down at the level of C, you're already allocating and deallocating by hand using the appropriate function calls, so it's not much to make sure your data is where you expect it to be. Personally, I'd rather it just fails if it's not where I expect it to be rather than do an additional check, so I don't like option 3. I do like the idea of checking relative to the executable as a default though, so I don't like option # 1.

There is a 4th option. You could leave it relative to the executable and just document what it's relative to. A comment above the al_open_map function could clear a lot up until this lib gets a wiki or something.

For me, I'd prefer option 2 or 4. If you don't like the idea of an extra parameter for al_open_map, you could do a variant of option 2 where you create a seperate function to check relative to the working directory. If you go with the seperate function way, just make sure there's one place that does the dirty work of actually loading the map.

**Comment by dradtke** [comment]
Okay, I pushed a fix to the branch in [this](https://github.com/dradtke/allegro_tiled/commit/ea59bb6536e333e79b83f1a8d6a01c59155d1a28) commit. I ended up doing a modified version of the new `al_open_map()` parameter, which is to have a global setting internal to the module that determines where paths are relative to, and provide a function to toggle it.

My reason for doing it this way is that it's entirely possible that developers would want to find maps relative to the working directory during development, but when it comes time to package, flip a couple switches and have it go back to checking relative to the executable. So rather than make people go hunting for calls to `al_open_map()`, it's now a single method call that changes the behavior of the entire program.

What do you think?

**Comment by ElectricSolstice** [comment]
It looks fine to me.
